export const javascriptRoutes = {
  javaScriptEquality: 'javascript_equality',
  main: 'javascript_main',
  IIFEScreen: 'IIFEScreen',
  bindMethodScreen: 'bindMethodScreen',
  constVsObjectFreezeScreen: 'constVsObjectFreezeScreen',
  javascriptGenerators: 'javascriptGenerators',
  javascriptHoisting: 'javascriptHoisting',
  temporaryDeadZone: 'temporaryDeadZone',
  mapVsForEach: 'mapVsForEach',
  nullVsUndefined: 'nullVsUndefined',
  weakMapVsMap: 'weakMapVsMap',
  valueOrReferenceLanguage: 'valueOrReferenceLanguage',
  javascriptClosures: 'javascriptClosures',
  javascriptClose: 'javascriptClose',
  javascriptStrict: 'javascriptStrict',
};
